# Generated by Django 5.2.4 on 2025-08-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sprefer', models.CharField(max_length=100)),
                ('sgmail', models.EmailField(max_length=254)),
                ('stimings', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('tprefer', models.CharField(max_length=100)),
                ('tgmail', models.EmailField(max_length=254)),
                ('ttimings', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('tTotalfee', models.CharField(max_length=20)),
                ('tfee', models.CharField(max_length=20)),
                ('ttime', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('tname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=100, null=True)),
                ('sprefer', models.CharField(blank=True, max_length=100, null=True)),
                ('sgmail', models.EmailField(max_length=254, unique=True)),
                ('stimings', models.CharField(blank=True, max_length=30, null=True)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'teacherstudent',
                'managed': False,
            },
        ),
    ]
